### ISSUE TITLE
关于封面的对齐问题

### ISSUE THREAD

**Issue by szq976** [hithesis/hithesis#194]
**请不要主动关闭 issue，如果问题已经解决并推送到 [dev](https://github.com/hithesis/hithesis/tree/dev) 分支，该 issue 会被打上 `fixed in dev` 的标签，并在合并到 [master](https://github.com/hithesis/hithesis/tree/master) 分支后关闭。** 
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：与word模板不符合

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：

## 描述模板不符合的具体信息   红线部分是对齐的 ，模板中的未对齐

窝工在（规范/word模板中）第（xxx）行规定格式为：

如图：
![未标题-3](https://github.com/hithesis/hithesis/assets/66050981/77ec4bf1-53c3-4d09-b5d0-e1f2b5c6402d)

![H)9J 6NAM_XIDK9](https://github.com/hithesis/hithesis/assets/66050981/7aea4a54-f8c5-4945-9227-c3e67e869792)

hithesis的格式为

如图：

如码：

**Comment by syvshc** [comment]
是被老师指出来要修改的吗？如果不是可以先不管它。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月18日(周日) 下午3:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [hithesis/hithesis] 关于封面的对齐问题 (Issue #194)




 
请不要主动关闭 issue，如果问题已经解决并推送到 dev 分支，该 issue 会被打上 fixed in dev 的标签，并在合并到 master 分支后关闭。
 
基本信息
  
 
校区（哈尔滨/威海/深圳？）：哈尔滨
 
 
 
学位（本/硕/博？）：博
 
 
 
论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文
 
 
 
证据（与规范不符/与word模板不符？）：与word模板不符合
 
 
 
证据所在网页（窝工规范或者word模板所在窝工官方网页）：
 
 
 
LaTeX 发行版（TeXLive 20xx/MikTeX/本模板不支持CTeX套装）：
 
 
 
模板版本（在 hithesis***.cls 中的 \ProvidesClass 命令中的 3.x.xx 或 3.xx 即为版本号）：
 
  
描述模板不符合的具体信息   红线部分是对齐的 ，模板中的未对齐
 
窝工在（规范/word模板中）第（xxx）行规定格式为：
 
如图：
 
 

 
hithesis的格式为
 
如图：
 
如码：

**Comment by szq976** [comment]
自己发现的。这个问题可以解决吗

**Comment by szq976** [comment]
明显硬伤

**Comment by syvshc** [comment]
硬不硬伤这个不会处理的，除非有老师指出来了。一个是这个模板有很多人用过并且成功毕业了，再一个是教务处Word版的改动很频繁，改了一个不会影响毕业的东西没准过一年封面又改了，不值当的

**Comment by szq976** [comment]
ok

**Comment by szq976** [comment]
可以私下给我弄下吗   50元怎么样   
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年6月18日 15:31
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [hithesis/hithesis] 关于封面的对齐问题 (Issue #194)
        
      
    
  

硬不硬伤这个不会处理的，除非有老师指出来了。一个是这个模板有很多人用过并且成功毕业了，再一个是教务处Word版的改动很频繁，改了一个不会影响毕业的东西没准过一年封面又改了，不值当的
