### ISSUE TITLE
中文逗号和冒号等不对

### ISSUE THREAD

**Issue by gengu2** [hithesis/hithesis#210]
**请不要主动关闭 issue，如果问题已经解决并推送到 [dev](https://github.com/hithesis/hithesis/tree/dev) 分支，该 issue 会被打上 `fixed in dev` 的标签，并在合并到 [master](https://github.com/hithesis/hithesis/tree/master) 分支后关闭。** 
## 基本信息

- 校区（哈尔滨/威海/深圳？）：深圳

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：与word模板不符

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive 2021

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：v3.1C

## 描述模板不符合的具体信息

中文符号明显错误
如图：

![0548](https://github.com/hithesis/hithesis/assets/56904603/a66d57a3-b4cf-4fe3-ab5f-abefdcc647c9)

**Comment by syvshc** [comment]
如果你是WINDOWS系统，将document class中的fontset从fandol改成windows



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月7日(周四) 中午11:07
收件人: ***@***.***&gt;;
抄送: "Sun ***@***.******@***.***&gt;;
主题: [hithesis/hithesis] 中文逗号和冒号等不对 (Issue #210)




 
请不要主动关闭 issue，如果问题已经解决并推送到 dev 分支，该 issue 会被打上 fixed in dev 的标签，并在合并到 master 分支后关闭。
 
基本信息
  
 
校区（哈尔滨/威海/深圳？）：深圳
 
 
 
学位（本/硕/博？）：博
 
 
 
论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文
 
 
 
证据（与规范不符/与word模板不符？）：与word模板不符
 
 
 
证据所在网页（窝工规范或者word模板所在窝工官方网页）：
 
 
 
LaTeX 发行版（TeXLive 20xx/MikTeX/本模板不支持CTeX套装）：TeXLive 2021
 
 
 
模板版本（在 hithesis***.cls 中的 \ProvidesClass 命令中的 3.x.xx 或 3.xx 即为版本号）：v3.1C
 
  
描述模板不符合的具体信息
 
中文符号明显错误
 如图：
 
0548.png (view on web)

**Comment by gengu2** [comment]
谢谢，已解决
